@startuml
'https://plantuml.com/class-diagram
skinparam defaultFontSize 32
skinparam ArrowFontSize 20

package shared.main {
	interface RootComp
	class RootComponent
	RootComponent : createChild(configuration) : Child
	class StackNavigation<Configuration>
	circle navigation <<internal function>>
	circle onFeatureOutput <<internal function>>
	class Child <<sealed>>
	class FeatureChild
	class Configuration <<sealed>>
	class FeatureConfiguration

	circle createComponent <<internal function>>
}

package shared.feature {
	interface FeatureComp
	class FeatureExecutor
	class FeatureComponent
	class Output
	FeatureComponent : componentContext: ComponentContext
}

package main {
	class RootActivity
	class RootContent <<Composable>>
}

package feature {
	class Screen <<Composable>>
}

shared.feature <-down- shared.main
feature <-down- main
shared.main <-down- main
shared.feature <-down- feature

RootComp <|-- RootComponent
Child <|-- FeatureChild
FeatureComponent *-- FeatureChild : contains
FeatureComponent *-- Screen : contains
FeatureExecutor *-- FeatureComponent : contains
FeatureComp <|-- FeatureComponent
Configuration <|-- FeatureConfiguration
FeatureComp <.. createComponent : creates
FeatureComponent <.. createComponent : creates
FeatureExecutor <.. createComponent : uses
Child <.. RootComponent : creates
Configuration <.. RootComponent : receives
Child <.. RootContent : receives
Output <.. onFeatureOutput : receives
Configuration <.. onFeatureOutput : creates
onFeatureOutput <.. RootComponent : uses
createComponent <.. RootComponent : uses
navigation <.. onFeatureOutput : adds Config to stack
Screen <.. RootContent : adds to stack
RootComp <|-- RootContent
FeatureConfiguration <.. RootContent : uses
RootComponent *-- RootActivity : contains
RootContent <|-- RootActivity
StackNavigation <|-- navigation

@enduml