package com.babestudios.companyinfouk.shared.domain

/**
 * This file was converted from a json resource, which was downloaded from
 * https://github.com/companieshouse/api-enumerations, and converted from yaml files.
 * This was done to simplify KMP resource handling, as moko-resources does not work with configuration cache:
 * https://github.com/icerockdev/moko-resources/issues/311
 */
@Suppress("LargeClass")
object ConstantMaps {

	val identificationType = mapOf(
		"non_eea" to "non_european_economic_area",
		"eea" to "european_economic_area"
	)

	val jurisdiction = mapOf(
		"england-wales" to "England/Wales",
		"wales" to "Wales ",
		"scotland" to "Scotland",
		"northern-ireland" to "Northern Ireland",
		"european-union" to "European Union",
		"united-kingdom" to "United Kingdom",
		"england" to "England",
		"noneu" to "Foreign (Non E.U.)"
	)

	val companySummary = mapOf(
		"other" to "Other",
		"private-unlimited" to "Private unlimited company",
		"ltd" to "Private limited Company",
		"plc" to "Public limited Company",
		"protected-cell-company" to "Protected Cell Company",
		"old-public-company" to "Old public company",
		"private-limited-guarant-nsc-limited-exemption" to
			"Private Limited Company by guarantee without share capital use of 'Limited' exemption",
		"limited-partnership" to "Limited partnership",
		"private-limited-guarant-nsc" to "Private company limited by guarantee without share capital",
		"converted-or-closed" to "Converted/closed company",
		"private-unlimited-nsc" to "Private unlimited company without share capital",
		"private-limited-shares-section-30-exemption" to "Private limited company use of 'Limited' exemption",
		"assurance-company" to "Assurance company",
		"oversea-company" to "Overseas company",
		"eeig" to "European economic interest grouping (EEIG)",
		"icvc-securities" to "Investment company with variable capital",
		"icvc-warrant" to "Investment company with variable capital",
		"icvc-umbrella" to "Investment company with variable capital",
		"registered-society-non-jurisdictional" to "Registered society",
		"industrial-and-provident-society" to "Industrial and provident Society",
		"northern-ireland" to "Northern Ireland company",
		"northern-ireland-other" to "Credit union (Northern Ireland)",
		"llp" to "Limited liability partnership",
		"royal-charter" to "Royal Charter company",
		"investment-company-with-variable-capital" to "Investment company with variable capital",
		"unregistered-company" to "Unregistered company",
		"european-public-limited-liability-company-se" to "European public limited liability company (SE)",
		"scottish-partnership" to "Scottish qualifying partnership",
		"charitable-incorporated-organisation" to "Charitable incorporated organisation",
		"scottish-charitable-incorporated-organisation" to "Scottish charitable incorporated organisation",
		"further-education-or-sixth-form-college-corporation" to "Further education or sixth form college corporation"
	)

	val companyType = mapOf(
		"private-unlimited" to "Private unlimited company",
		"ltd" to "Private limited company",
		"plc" to "Public limited company",
		"old-public-company" to "Old public company",
		"private-limited-guarant-nsc-limited-exemption" to
			"Private Limited Company by guarantee without share capital, use of 'Limited' exemption",
		"limited-partnership" to "Limited partnership",
		"private-limited-guarant-nsc" to "Private limited by guarantee without share capital",
		"converted-or-closed" to "Converted / closed",
		"private-unlimited-nsc" to "Private unlimited company without share capital",
		"private-limited-shares-section-30-exemption" to "Private Limited Company, use of 'Limited' exemption",
		"protected-cell-company" to "Protected cell company",
		"assurance-company" to "Assurance company",
		"oversea-company" to "Overseas company",
		"eeig" to "European economic interest grouping (EEIG)",
		"icvc-securities" to "Investment company with variable capital",
		"icvc-warrant" to "Investment company with variable capital",
		"icvc-umbrella" to "Investment company with variable capital",
		"registered-society-non-jurisdictional" to "Registered society",
		"industrial-and-provident-society" to "Industrial and provident society",
		"northern-ireland" to "Northern Ireland company",
		"northern-ireland-other" to "Credit union (Northern Ireland)",
		"llp" to "Limited liability partnership",
		"royal-charter" to "Royal charter company",
		"investment-company-with-variable-capital" to "Investment company with variable capital",
		"unregistered-company" to "Unregistered company",
		"other" to "Other company type",
		"european-public-limited-liability-company-se" to "European public limited liability company (SE)",
		"uk-establishment" to "UK establishment company",
		"scottish-partnership" to "Scottish qualifying partnership",
		"charitable-incorporated-organisation" to "Charitable incorporated organisation",
		"scottish-charitable-incorporated-organisation" to "Scottish charitable incorporated organisation",
		"further-education-or-sixth-form-college-corporation" to "Further education or sixth form college corporation"
	)

	val companySubtype = mapOf(
		"community-interest-company" to "Community Interest Company (CIC)",
		"private-fund-limited-partnership" to "Private Fund Limited Partnership (PFLP)"
	)

	val companyBirthType = mapOf(
		"private-unlimited" to "Incorporated on",
		"ltd" to "Incorporated on",
		"plc" to "Incorporated on",
		"old-public-company" to "Incorporated on",
		"private-limited-guarant-nsc-limited-exemption" to "Incorporated on",
		"limited-partnership" to "Registered on",
		"private-limited-guarant-nsc" to "Incorporated on",
		"converted-or-closed" to "Incorporated on",
		"private-unlimited-nsc" to "Incorporated on",
		"private-limited-shares-section-30-exemption" to "Incorporated on",
		"assurance-company" to "Registered on",
		"oversea-company" to "First UK establishment opened on",
		"eeig" to "Registered on",
		"icvc-securities" to "Incorporated on",
		"icvc-warrant" to "Incorporated on",
		"icvc-umbrella" to "Incorporated on",
		"industrial-and-provident-society" to "Incorporated on",
		"northern-ireland" to "Incorporated on",
		"northern-ireland-other" to "Incorporated on",
		"llp" to "Incorporated on",
		"royal-charter" to "Incorporated on",
		"investment-company-with-variable-capital" to "Incorporated on",
		"unregistered-company" to "Formed on",
		"other" to "Incorporated on",
		"european-public-limited-liability-company-se" to "Formed on",
		"uk-establishment" to "Opened on",
		"scottish-partnership" to "Registered on",
		"further-education-or-sixth-form-college-corporation" to "Registered on"
	)

	val proofStatus = mapOf(
		"paper" to "PAPER",
		"electronic" to "ELECTRONIC",
		"statutory" to "STATUTORY",
		"in-dispute" to "IN DISPUTE",
		"pending" to "PENDING"
	)

	val companyStatus = mapOf(
		"active" to "Active",
		"dissolved" to "Dissolved",
		"liquidation" to "Liquidation",
		"receivership" to "Receiver Action",
		"converted-closed" to "Converted / Closed",
		"voluntary-arrangement" to "Voluntary Arrangement",
		"insolvency-proceedings" to "Insolvency Proceedings",
		"administration" to "In Administration",
		"open" to "Open",
		"closed" to "Closed"
	)

	val companyStatusDetail = mapOf(
		"active" to "",
		"dissolved" to "",
		"converted-closed" to "",
		"transferred-from-uk" to "Transfer from UK",
		"active-proposal-to-strike-off" to "Active proposal to strike off",
		"petition-to-restore-dissolved" to "Petition to restore dissolved",
		"transformed-to-se" to "Transformed to SE",
		"converted-to-plc" to "Converted to PLC"
	)

	val foreignAccountType = mapOf(
		"accounting-requirements-of-originating-country-apply" to "Accounting requirements of originating country apply",
		"accounting-requirements-of-originating-country-do-not-apply" to
			"Accounting requirements of originating country do not apply"
	)

	val termsOfAccountPublication = mapOf(
		"accounts-publication-date-supplied-by-company" to "Accounts publication date supplied by company",
		"accounting-publication-date-does-not-need-to-be-supplied-by-company" to
			"Accounts publication date does not need to be supplied by company",
		"accounting-reference-date-allocated-by-companies-house" to "Accounting reference date allocated by Companies House"
	)

	val accountType = mapOf(
		"null" to "Null",
		"full" to "Full",
		"small" to "Small",
		"medium" to "Medium",
		"group" to "Group",
		"dormant" to "Dormant",
		"interim" to "Interim",
		"initial" to "Initial",
		"total-exemption-full" to "Total Exemption Full",
		"total-exemption-small" to "Total Exemption Small",
		"partial-exemption" to "Partial Exemption",
		"audit-exemption-subsidiary" to "Audit Exemption Subsidiary",
		"filing-exemption-subsidiary" to "Filing Exemption Subsidiary",
		"micro-entity" to "Micro Entity"
	)

	val officerRole = mapOf(
		"cic-manager" to "CIC Manager",
		"corporate-director" to "Director",
		"corporate-llp-designated-member" to "LLP Designated Member",
		"corporate-llp-member" to "LLP Member",
		"corporate-manager-of-an-eeig" to "Manager of an EEIG",
		"corporate-member-of-a-management-organ" to "Member of a Management Organ",
		"corporate-member-of-a-supervisory-organ" to "Member of a Supervisory Organ",
		"corporate-member-of-an-administrative-organ" to "Member of an Administrative Organ",
		"corporate-nominee-director" to "Nominee Director",
		"corporate-nominee-secretary" to "Nominee Secretary",
		"corporate-secretary" to "Secretary",
		"director" to "Director",
		"general-partner-in-a-limited-partnership" to "General Partner in a Limited Partnership",
		"judicial-factor" to "Judicial Factor",
		"limited-partner-in-a-limited-partnership" to "Limited Partner in a Limited Partnership",
		"llp-designated-member" to "LLP Designated Member",
		"llp-member" to "LLP Member",
		"manager-of-an-eeig" to "Manager of an EEIG",
		"member-of-a-management-organ" to "Member of a Management Organ",
		"member-of-a-supervisory-organ" to "Member of a Supervisory Organ",
		"member-of-an-administrative-organ" to "Member of an Administrative Organ",
		"nominee-director" to "Nominee Director",
		"nominee-secretary" to "Nominee Secretary",
		"person-authorised-to-accept" to "Person Authorised to Accept",
		"person-authorised-to-represent" to "Person Authorised to Represent",
		"person-authorised-to-represent-and-accept" to "Person Authorised to Represent and Accept",
		"receiver-and-manager" to "Receiver and Manager",
		"secretary" to "Secretary"
	)

	val filingType = mapOf(
		"change-registered-office-address" to "Change of registered office address"
	)

	val filingStatus = mapOf(
		"in-progress" to "In Progress",
		"queued" to "Queued",
		"processing" to "Processing",
		"accepted" to "Accepted",
		"rejected" to "Rejected"
	)

	val insolvencyCaseType = mapOf(
		"compulsory-liquidation" to "Compulsory liquidation",
		"in-administration" to "In administration",
		"creditors-voluntary-liquidation" to "Creditors voluntary liquidation",
		"members-voluntary-liquidation" to "Members voluntary liquidation",
		"foreign-insolvency" to "Foreign insolvency",
		"administrative-receiver" to "Administrative receiver appointed",
		"scottish-administrative-receiver" to "Receiver (Scotland) appointed",
		"administration-order" to "Administration order",
		"corporate-voluntary-arrangement" to "Corporate voluntary arrangement (CVA)",
		"receiver-manager" to "Receiver/Manager appointed",
		"corporate-voluntary-arrangement-moratorium" to "Corporate voluntary arrangement moratorium"
	)

	val insolvencyCaseDateType = mapOf(
		"wound-up-on" to "Commencement of winding up",
		"petitioned-on" to "Petition date",
		"concluded-winding-up-on" to "Conclusion of winding up",
		"due-to-be-dissolved-on" to "Due to be dissolved on",
		"dissolved-on" to "Dissolved on",
		"administration-started-on" to "Administration started",
		"administration-ended-on" to "Administration ended",
		"administration-discharged-on" to "Administration discharged",
		"instrumented-on" to "Instrument date",
		"moratorium-started-on" to "Moratorium start date",
		"ordered-to-wind-up-on" to "Ordered to wind up",
		"voluntary-arrangement-started-on" to "Date of meeting to approve CVA",
		"voluntary-arrangement-ended-on" to "Date of completion or termination of CVA",
		"declaration-solvent-on" to "Declaration of solvency sworn on"
	)

	val sicDescriptions = mapOf(
		"1010" to "Mining & agglomeration of hard coal",
		"1020" to "Mining and agglomeration of lignite",
		"1030" to "Extraction and agglomeration of peat",
		"1110" to "Extraction petroleum & natural gas",
		"1120" to "Services to oil and gas extraction",
		"1200" to "Mining of uranium & thorium ores",
		"1310" to "Mining of iron ores",
		"1320" to "Mining non-ferrous metal ores",
		"1411" to "Quarrying of stone for construction",
		"1412" to "Quarry of limestone, gypsum & chalk",
		"1413" to "Quarrying of slate",
		"1421" to "Operation of gravel and sand pits",
		"1422" to "Mining of clays and kaolin",
		"1430" to "Mine chemical & fertiliser minerals",
		"1440" to "Production of salt",
		"1450" to "Other mining and quarrying",
		"1511" to "Production and preserving of meat",
		"1512" to "Production & preserve poultry meat",
		"1513" to "Production meat & poultry products",
		"1520" to "Process & preserve fish & products",
		"1531" to "Processing & preserve potatoes",
		"1532" to "Manufacture of fruit & vegetable juice",
		"1533" to "Process etc. fruit, vegetables",
		"1541" to "Manufacture of crude oils and fats",
		"1542" to "Manufacture of refined oils & fats",
		"1543" to "Manufacture margarine & similar edible fats",
		"1551" to "Operation dairies & cheese making",
		"1552" to "Manufacture of ice cream",
		"1561" to "Manufacture of grain mill products",
		"1562" to "Manufacture of starches & starch products",
		"1571" to "Manufacture of prepared farm animal feeds",
		"1572" to "Manufacture of prepared pet foods",
		"1581" to "Manufacture of bread, fresh pastry & cakes",
		"1582" to "Manufacture biscuits, preserved pastry etc.",
		"1583" to "Manufacture of sugar",
		"1584" to "Manufacture cocoa, chocolate, confectionery",
		"1585" to "Manufacture macaroni & similar farinaceous",
		"1586" to "Processing of tea and coffee",
		"1587" to "Manufacture of condiments & seasonings",
		"1588" to "Manufacture of homogenised & dietetic food",
		"1589" to "Manufacture of other food products",
		"1591" to "Manufacture distilled potable alcoholic drinks",
		"1592" to "Ethyl alcohol fermented materials",
		"1593" to "Manufacture of wines",
		"1594" to "Manufacture of cider & other fruit wines",
		"1595" to "Manufacture other non-distilled fermented drinks",
		"1596" to "Manufacture of beer",
		"1597" to "Manufacture of malt",
		"1598" to "Produce mineral water, soft drinks",
		"1600" to "Manufacture of tobacco products",
		"1711" to "Prepare & spin cotton-type fibres",
		"1712" to "Prepare & spin woollen-type fibres",
		"1713" to "Prepare & spin worsted-type fibres",
		"1714" to "Preparation & spin flax-type fibres",
		"1715" to "Throw & prepare silk, synthetic etc.",
		"1716" to "Manufacture of sewing threads",
		"1717" to "Preparation & spin of other textiles",
		"1721" to "Cotton-type weaving",
		"1722" to "Woollen-type weaving",
		"1723" to "Worsted-type weaving",
		"1724" to "Silk-type weaving",
		"1725" to "Other textile weaving",
		"1730" to "Finishing of textiles",
		"1740" to "Manufacture made-up textiles, not apparel",
		"1751" to "Manufacture of carpet and rugs",
		"1752" to "Manufacture cordage, rope, twine & netting",
		"1753" to "Manufacture nonwovens & goods, not apparel",
		"1754" to "Manufacture of other textiles",
		"1760" to "Manufacture of knitted & crocheted fabrics",
		"1771" to "Manufacture of knitted & crocheted hosiery",
		"1772" to "Manufacture knit & crocheted pullovers, etc.",
		"1810" to "Manufacture of leather clothes",
		"1821" to "Manufacture of workwear",
		"1822" to "Manufacture of other outerwear",
		"1823" to "Manufacture of underwear",
		"1824" to "Manufacture other wearing apparel etc.",
		"1830" to "Dress & dye fur; manufacture fur articles",
		"1910" to "Tanning and dressing of leather",
		"1920" to "Manufacture of luggage & the like, saddlery",
		"1930" to "Manufacture of footwear",
		"2010" to "Sawmill, plane, impregnation wood",
		"2020" to "Manufacture of veneer sheets, plywood, etc.",
		"2030" to "Manufacture builders carpentry & joinery",
		"2040" to "Manufacture of wooden containers",
		"2051" to "Manufacture of other products of wood",
		"2052" to "Manufacture of articles of cork, straw etc.",
		"2111" to "Manufacture of pulp",
		"2112" to "Manufacture of paper & paperboard",
		"2121" to "Manufacture of cartons",
		"2122" to "Manufacture of household & toilet goods",
		"2123" to "Manufacture of paper stationery",
		"2124" to "Manufacture of wallpaper",
		"2125" to "Manufacture of paper & paperboard goods",
		"2211" to "Publishing of books",
		"2212" to "Publishing of newspapers",
		"2213" to "Publish journals & periodicals",
		"2214" to "Publishing of sound recordings",
		"2215" to "Other publishing",
		"2221" to "Printing of newspapers",
		"2222" to "Printing not elsewhere classified",
		"2223" to "Bookbinding and finishing",
		"2224" to "Pre-press activities",
		"2225" to "Ancillary printing operations",
		"2231" to "Reproduction of sound recording",
		"2232" to "Reproduction of video recording",
		"2233" to "Reproduction of computer media",
		"2310" to "Manufacture of coke oven products",
		"2320" to "Manufacture of refined petroleum products",
		"2330" to "Processing of nuclear fuel",
		"2411" to "Manufacture of industrial gases",
		"2412" to "Manufacture of dyes and pigments",
		"2413" to "Manufacture other inorganic basic chemicals",
		"2414" to "Manufacture other organic basic chemicals",
		"2415" to "Manufacture fertilisers, nitrogen compounds",
		"2416" to "Manufacture of plastics in primary forms",
		"2417" to "Manufacture synthetic rubber primary forms",
		"2420" to "Manufacture of pesticides & agro-chemicals",
		"2430" to "Manufacture of paints, print ink & mastics etc.",
		"2441" to "Manufacture of basic pharmaceutical prods",
		"2442" to "Manufacture of pharmaceutical preparations",
		"2451" to "Manufacture soap & detergents, polishes etc.",
		"2452" to "Manufacture perfumes & toilet preparations",
		"2461" to "Manufacture of explosives",
		"2462" to "Manufacture of glues and gelatines",
		"2463" to "Manufacture of essential oils",
		"2464" to "Manufacture photograph chemical material",
		"2465" to "Manufacture of prepared unrecorded media",
		"2466" to "Manufacture of other chemical products",
		"2470" to "Manufacture of man-made fibres",
		"2511" to "Manufacture of rubber tyres & tubes",
		"2512" to "Retread & rebuild rubber tyres",
		"2513" to "Manufacture of other rubber products",
		"2521" to "Manufacture of plastic plates, sheets, etc.",
		"2522" to "Manufacture of plastic pack goods",
		"2523" to "Manufacture of builders ware of plastic",
		"2524" to "Manufacture of other plastic products",
		"2611" to "Manufacture of flat glass",
		"2612" to "Shaping & process of flat glass",
		"2613" to "Manufacture of hollow glass",
		"2614" to "Manufacture of glass fibres",
		"2615" to "Manufacture other glass inc. technical",
		"2621" to "Manufacture of ceramic household etc. goods",
		"2622" to "Manufacture of ceramic sanitary fixtures",
		"2623" to "Manufacture of ceramic insulators etc.",
		"2624" to "Manufacture other technical ceramic goods",
		"2625" to "Manufacture of other ceramic products",
		"2626" to "Manufacture of refractory ceramic products",
		"2630" to "Manufacture of ceramic tiles & flags",
		"2640" to "Manufacture of bricks, etc. in baked clay",
		"2651" to "Manufacture of cement",
		"2652" to "Manufacture of lime",
		"2653" to "Manufacture of plaster",
		"2661" to "Manufacture concrete goods for construction",
		"2662" to "Manufacture plaster goods for construction",
		"2663" to "Manufacture of ready-mixed concrete",
		"2664" to "Manufacture of mortars",
		"2665" to "Manufacture of fibre cement",
		"2666" to "Manufacture other articles of concrete, etc.",
		"2670" to "Cutting, shaping & finish stone",
		"2681" to "Production of abrasive products",
		"2682" to "Manufacture other non-metal mineral",
		"2710" to "Manufacture of basic iron & steel & of Ferro-alloys ",
		"2721" to "Manufacture of cast iron tubes",
		"2722" to "Manufacture of steel tubes",
		"2731" to "Cold drawing",
		"2732" to "Cold rolling of narrow strips",
		"2733" to "Cold forming or folding",
		"2734" to "Wire drawing",
		"2735" to "Other 1st process iron & steel",
		"2741" to "Precious metals production",
		"2742" to "Aluminium production",
		"2743" to "Lead, zinc and tin production",
		"2744" to "Copper production",
		"2745" to "Other non-ferrous metal production",
		"2751" to "Casting of iron",
		"2752" to "Casting of steel",
		"2753" to "Casting of light metals",
		"2754" to "Casting of other non-ferrous metals",
		"2811" to "Manufacture metal structures & parts",
		"2812" to "Manufacture builders carpentry of metal",
		"2821" to "Manufacture tanks, etc. & metal containers",
		"2822" to "Manufacture central heating rads & boilers",
		"2830" to "Manufacture steam generators, not boilers",
		"2840" to "Forge press stamp & roll form metal",
		"2851" to "Treatment and coat metals",
		"2852" to "General mechanical engineering",
		"2861" to "Manufacture of cutlery",
		"2862" to "Manufacture of tools",
		"2863" to "Manufacture of locks and hinges",
		"2871" to "Manufacture steel drums, similar containers",
		"2872" to "Manufacture of light metal packaging",
		"2873" to "Manufacture of wire products",
		"2874" to "Manufacture fasteners, screw, chains etc.",
		"2875" to "Manufacture other fabricated metal products",
		"2911" to "Manufacture engines, not aircraft, etc.",
		"2912" to "Manufacture of pumps & compressors",
		"2913" to "Manufacture of taps and valves",
		"2914" to "Manufacture bearings, gears, gear etc.",
		"2921" to "Manufacture of furnaces & furnace burners",
		"2922" to "Manufacture of lift & handling equipment",
		"2923" to "Manufacture non-domestic ventilation",
		"2924" to "Manufacture of other general machinery",
		"2931" to "Manufacture of agricultural tractors",
		"2932" to "Manufacture other agric. & forestry machines",
		"2940" to "Manufacture of machine tools",
		"2941" to "Manufacture of portable hand held power tools",
		"2942" to "Manufacture of metalworking tools",
		"2943" to "Manufacture of other machine tools not elsewhere classified",
		"2951" to "Manufacture of machinery for metallurgy",
		"2952" to "Manufacture machines for mining, quarry etc.",
		"2953" to "Manufacture for food, beverage & tobacco",
		"2954" to "Manufacture for textile, apparel & leather",
		"2955" to "Manufacture machinery for paper & board",
		"2956" to "Manufacture other special purpose machine",
		"2960" to "Manufacture of weapons & ammunition",
		"2971" to "Manufacture of electric domestic appliances",
		"2972" to "Manufacture non-electric domestic appliances",
		"3001" to "Manufacture of office machinery",
		"3002" to "Manufacture computers & process equipment",
		"3110" to "Manufacture electric motors, generators etc.",
		"3120" to "Manufacture electricity distribution etc.",
		"3130" to "Manufacture of insulated wire & cable",
		"3140" to "Manufacture of accumulators, batteries etc.",
		"3150" to "Manufacture lighting equipment & lamps",
		"3161" to "Manufacture electric equipment, engines etc.",
		"3162" to "Manufacture other electrical equipment",
		"3210" to "Manufacture of electronic components",
		"3220" to "Manufacture TV transmitters, telephony etc.",
		"3230" to "Manufacture TV & radio, sound or video etc.",
		"3310" to "Manufacture medical, orthopaedic etc. equipment ",
		"3320" to "Manufacture instruments for measuring etc.",
		"3330" to "Manufacture indust process control equipment",
		"3340" to "Manufacture optical, photographic etc. equipment ",
		"3350" to "Manufacture of watches and clocks",
		"3410" to "Manufacture of motor vehicles",
		"3420" to "Manufacture motor vehicle bodies etc.",
		"3430" to "Manufacture motor vehicle & engine parts",
		"3511" to "Building and repairing of ships",
		"3512" to "Build & repair pleasure & sport boats",
		"3520" to "Manufacture of railway locomotives & stock",
		"3530" to "Manufacture of aircraft & spacecraft",
		"3541" to "Manufacture of motorcycles",
		"3542" to "Manufacture of bicycles",
		"3543" to "Manufacture of invalid carriages",
		"3550" to "Manufacture other transport equipment",
		"3611" to "Manufacture of chairs and seats",
		"3612" to "Manufacture other office & shop furniture",
		"3613" to "Manufacture of other kitchen furniture",
		"3614" to "Manufacture of other furniture",
		"3615" to "Manufacture of mattresses",
		"3621" to "Striking of coins and medals",
		"3622" to "Manufacture of jewellery & related",
		"3630" to "Manufacture of musical instruments",
		"3640" to "Manufacture of sports goods",
		"3650" to "Manufacture of games and toys",
		"3661" to "Manufacture of imitation jewellery",
		"3662" to "Manufacture of brooms and brushes",
		"3663" to "Other manufacturing",
		"3710" to "Recycling of metal waste and scrap",
		"3720" to "Recycling non-metal waste & scrap",
		"4010" to "Production",
		"4011" to "Production of electricity",
		"4012" to "Transmission of electricity",
		"4013" to "Distribution & trade in electricity",
		"4020" to "Mfr of gas; mains distribution",
		"4021" to "Manufacture of gas",
		"4022" to "Distribution & trade of gaseous fuels through mains",
		"4030" to "Steam and hot water supply",
		"4100" to "Collection, purify etc. of water",
		"4511" to "Demolition buildings; earth moving",
		"4512" to "Test drilling and boring",
		"4521" to "General construction & civil engineer",
		"4522" to "Erection of roof covering & frames",
		"4523" to "Construction roads, airfields etc.",
		"4524" to "Construction of water projects",
		"4525" to "Other special trades construction",
		"4531" to "Installation electrical wiring etc.",
		"4532" to "Insulation work activities",
		"4533" to "Plumbing",
		"4534" to "Other building installation",
		"4541" to "Plastering",
		"4542" to "Joinery installation",
		"4543" to "Floor and wall covering",
		"4544" to "Painting and glazing",
		"4545" to "Other building completion",
		"4550" to "Rent construction equipment with operator",
		"5010" to "Sale of motor vehicles",
		"5020" to "Maintenance & repair of motors",
		"5030" to "Sale of motor vehicle parts etc.",
		"5040" to "Sale, repair etc. motorcycles & parts",
		"5050" to "Retail sale of automotive fuel",
		"5111" to "Agents agric & textile materials",
		"5112" to "Agents in sale of fuels, ores, etc.",
		"5113" to "Agents in building materials",
		"5114" to "Agents in industrial equipment, etc.",
		"5115" to "Agents in household goods, etc.",
		"5116" to "Agents in textiles, footwear etc.",
		"5117" to "Agents in food, drink & tobacco",
		"5118" to "Agents in particular products",
		"5119" to "Agents in sale of variety of goods",
		"5121" to "Wholesale of grain, animal feeds",
		"5122" to "Wholesale of flowers and plants",
		"5123" to "Wholesale of live animals",
		"5124" to "Wholesale hides, skins and leather",
		"5125" to "Wholesale of unmanufactured tobacco",
		"5131" to "Wholesale of fruit and vegetables",
		"5132" to "Wholesale of meat and meat products",
		"5133" to "Wholesale dairy products",
		"5134" to "Wholesale of alcohol and other drinks",
		"5135" to "Wholesale of tobacco products",
		"5136" to "Wholesale sugar, chocolate etc.",
		"5137" to "Wholesale coffee, tea, cocoa etc.",
		"5138" to "Wholesale other food inc fish, etc.",
		"5139" to "Non-specialised wholesale food, etc.",
		"5141" to "Wholesale of textiles",
		"5142" to "Wholesale of clothing and footwear",
		"5143" to "Wholesale electric household goods",
		"5144" to "Wholesale of china, wallpaper etc.",
		"5145" to "Wholesale of perfume and cosmetics",
		"5146" to "Wholesale of pharmaceutical goods",
		"5147" to "Wholesale of other household goods",
		"5151" to "Wholesale fuels & related products",
		"5152" to "Wholesale of metals and metal ores",
		"5153" to "Wholesale wood, construction etc.",
		"5154" to "Wholesale hardware, plumbing etc.",
		"5155" to "Wholesale of chemical products",
		"5156" to "Wholesale other intermediate goods",
		"5157" to "Wholesale of waste and scrap",
		"5161" to "Wholesale of machine tools",
		"5162" to "Wholesale of construction machinery",
		"5163" to "Wholesale textile industry machines",
		"5164" to "Wholesale office machinery & equip",
		"5165" to "Wholesale machines",
		"5166" to "Wholesale agric machines & tractors",
		"5170" to "Other wholesale",
		"5181" to "Wholesale of machine tools",
		"5182" to "Wholesale of mining",
		"5183" to "Wholesale of machinery for the textile industry",
		"5184" to "Wholesale of computers",
		"5185" to "Wholesale of other office machinery & equipment",
		"5186" to "Wholesale of other electronic parts & equipment",
		"5187" to "Wholesale of other machinery for use in industry",
		"5188" to "Wholesale of agricultural machinery & accessories & implements",
		"5190" to "Other wholesale",
		"5211" to "Retail in non-specialised stores holding an alcohol licence",
		"5212" to "Other retail non-specialised stores",
		"5221" to "Retail of fruit and vegetables",
		"5222" to "Retail of meat and meat products",
		"5223" to "Retail of fish, crustaceans etc.",
		"5224" to "Retail bread, cakes, confectionery",
		"5225" to "Retail alcoholic & other beverages",
		"5226" to "Retail sale of tobacco products",
		"5227" to "Other retail food etc. specialised",
		"5231" to "Dispensing chemists",
		"5232" to "Retail medical & orthopaedic goods",
		"5233" to "Retail cosmetic & toilet articles",
		"5241" to "Retail sale of textiles",
		"5242" to "Retail sale of clothing",
		"5243" to "Retail of footwear & leather goods",
		"5244" to "Retail furniture household etc",
		"5245" to "Retail electric household, etc. goods",
		"5246" to "Retail hardware, paints & glass",
		"5247" to "Retail books, newspapers etc.",
		"5248" to "Other retail specialist stores",
		"5250" to "Retail other secondhand goods",
		"5261" to "Retail sale via mail order houses",
		"5262" to "Retail sale via stalls and markets",
		"5263" to "Other non-store retail sale",
		"5271" to "Repair boots, shoes, leather goods",
		"5272" to "Repair electrical household goods",
		"5273" to "Repair of clocks & jewellery",
		"5274" to "Repair not elsewhere classified",
		"5510" to "Hotels & motels with or without restaurant",
		"5511" to "Hotels & motels",
		"5512" to "Hotels & motels",
		"5521" to "Youth hostels and mountain refuges",
		"5522" to "Camp sites, including caravan sites",
		"5523" to "Other provision of lodgings",
		"5530" to "Restaurants",
		"5540" to "Bars",
		"5551" to "Canteens",
		"5552" to "Catering",
		"6010" to "Transport via railways",
		"6021" to "Other scheduled passenger land transport",
		"6022" to "Taxi operation",
		"6023" to "Other passenger land transport",
		"6024" to "Freight transport by road",
		"6030" to "Transport via pipelines",
		"6110" to "Sea and coastal water transport",
		"6120" to "Inland water transport",
		"6210" to "Scheduled air transport",
		"6220" to "Non-scheduled air transport",
		"6230" to "Space transport",
		"6311" to "Cargo handling",
		"6312" to "Storage & warehousing",
		"6321" to "Other supporting land transport",
		"6322" to "Other supporting water transport",
		"6323" to "Other supporting air transport",
		"6330" to "Travel agencies etc; tourist",
		"6340" to "Other transport agencies",
		"6411" to "National post activities",
		"6412" to "Courier other than national post",
		"6420" to "Telecommunications",
		"6511" to "Central banking",
		"6512" to "Other monetary intermediation",
		"6521" to "Financial leasing",
		"6522" to "Other credit granting",
		"6523" to "Other financial intermediation",
		"6601" to "Life insurance/reinsurance",
		"6602" to "Pension funding",
		"6603" to "Non-life insurance/reinsurance",
		"6711" to "Administration of financial markets",
		"6712" to "Security broking & fund management",
		"6713" to "Auxiliary financial intermed",
		"6720" to "Auxiliary insurance & pension fund",
		"7011" to "Development & sell real estate",
		"7012" to "Buying & sell own real estate",
		"7020" to "Letting of own property",
		"7031" to "Real estate agencies",
		"7032" to "Manage real estate, fee or contract",
		"7110" to "Renting of automobiles",
		"7121" to "Rent other land transport equipment",
		"7122" to "Rent water transport equipment",
		"7123" to "Renting of air transport equipment",
		"7131" to "Rent agricultural machinery & equip",
		"7132" to "Rent civil engineering machinery",
		"7133" to "Rent office machinery inc computers",
		"7134" to "Rent other machinery & equip",
		"7140" to "Rent personal & household goods",
		"7210" to "Hardware consultancy",
		"7220" to "Software consultancy and supply",
		"7221" to "Software publishing",
		"7222" to "Other software consultancy and supply",
		"7230" to "Data processing",
		"7240" to "Data base activities",
		"7250" to "Maintenance office & computing mach",
		"7260" to "Other computer related activities",
		"7310" to "R & d on nat sciences & engineering",
		"7320" to "R & d on soc sciences & humanities",
		"7411" to "Legal activities",
		"7412" to "Accounting, auditing; tax consult",
		"7413" to "Market research, opinion polling",
		"7414" to "Business & management consultancy",
		"7415" to "Holding companies including Head Offices",
		"7420" to "Architectural, technical consult",
		"7430" to "Technical testing and analysis",
		"7440" to "Advertising",
		"7450" to "Labour recruitment",
		"7460" to "Investigation & security",
		"7470" to "Other cleaning activities",
		"7481" to "Portrait photographic activities",
		"7482" to "Packaging activities",
		"7483" to "Secretarial & translation",
		"7484" to "Other business activities",
		"7485" to "Secretarial & translation services",
		"7486" to "Call centre activities",
		"7487" to "Other business activities",
		"7499" to "Non-trading company",
		"7511" to "General (overall) public service",
		"7512" to "Regulation health, education, etc.",
		"7513" to "Regulation more efficient business",
		"7514" to "Support services for government",
		"7521" to "Foreign affairs",
		"7522" to "Defence activities",
		"7523" to "Justice and judicial activities",
		"7524" to "Public security, law & order",
		"7525" to "Fire service activities",
		"7530" to "Compulsory social security",
		"8010" to "Primary education",
		"8021" to "General secondary education",
		"8022" to "Technical & vocational secondary",
		"8030" to "Higher education",
		"8041" to "Driving school activities",
		"8042" to "Adult and other education",
		"8511" to "Hospital activities",
		"8512" to "Medical practice activities",
		"8513" to "Dental practice activities",
		"8514" to "Other human health activities",
		"8520" to "Veterinary activities",
		"8531" to "Social work with accommodation",
		"8532" to "Social work without accommodation",
		"9000" to "Refuse disposal",
		"9001" to "Collection and treatment of sewage",
		"9002" to "Collection and treatment of other waste",
		"9003" to "Sanitation remediation and similar activities",
		"9111" to "Business & employers organisations",
		"9112" to "Professional organisations",
		"9120" to "Trade unions",
		"9131" to "Religious organisations",
		"9132" to "Political organisations",
		"9133" to "Other membership organisations",
		"9211" to "Motion picture and video production",
		"9212" to "Motion picture & video distribution",
		"9213" to "Motion picture projection",
		"9220" to "Radio and television activities",
		"9231" to "Artistic & literary creation etc",
		"9232" to "Operation of arts facilities",
		"9233" to "Fair and amusement park activities",
		"9234" to "Other entertainment activities",
		"9240" to "News agency activities",
		"9251" to "Library and archives activities",
		"9252" to "Museum & preservation of history",
		"9253" to "Botanical, zoos & nature reserves",
		"9261" to "Operate sports arenas & stadiums",
		"9262" to "Other sporting activities",
		"9271" to "Gambling and betting activities",
		"9272" to "Other recreational activities nec",
		"9301" to "Wash & dry clean textile & fur",
		"9302" to "Hairdressing & other beauty treatment",
		"9303" to "Funeral and related activities",
		"9304" to "Physical well-being activities",
		"9305" to "Other service activities n.e.c.",
		"9500" to "Private household with employees",
		"9600" to "Undifferentiated goods producing activities of private households for own use",
		"9700" to "Undifferentiated services producing activities of private households for own use",
		"9800" to "Residents property management",
		"9900" to "Extra-territorial organisations",
		"9999" to "Dormant company",
		"10110" to "Processing and preserving of meat",
		"10120" to "Processing and preserving of poultry meat",
		"10130" to "Production of meat and poultry meat products",
		"10200" to "Processing and preserving of fish, crustaceans and molluscs",
		"10310" to "Processing and preserving of potatoes",
		"10320" to "Manufacture of fruit and vegetable juice",
		"10390" to "Other processing and preserving of fruit and vegetables",
		"10410" to "Manufacture of oils and fats",
		"10420" to "Manufacture of margarine and similar edible fats",
		"10511" to "Liquid milk and cream production",
		"10512" to "Butter and cheese production",
		"10519" to "Manufacture of other milk products",
		"10520" to "Manufacture of ice cream",
		"10611" to "Grain milling",
		"10612" to "Manufacture of breakfast cereals and cereals-based food",
		"10620" to "Manufacture of starches and starch products",
		"10710" to "Manufacture of bread; manufacture of fresh pastry goods and cakes",
		"10720" to "Manufacture of rusks and biscuits; manufacture of preserved pastry goods and cakes",
		"10730" to "Manufacture of macaroni, noodles, couscous and similar farinaceous products",
		"10810" to "Manufacture of sugar",
		"10821" to "Manufacture of cocoa and chocolate confectionery",
		"10822" to "Manufacture of sugar confectionery",
		"10831" to "Tea processing",
		"10832" to "Production of coffee and coffee substitutes",
		"10840" to "Manufacture of condiments and seasonings",
		"10850" to "Manufacture of prepared meals and dishes",
		"10860" to "Manufacture of homogenised food preparations and dietetic food",
		"10890" to "Manufacture of other food products not elsewhere classified",
		"10910" to "Manufacture of prepared feeds for farm animals",
		"10920" to "Manufacture of prepared pet foods",
		"11010" to "Distilling, rectifying and blending of spirits",
		"11020" to "Manufacture of wine from grape",
		"11030" to "Manufacture of cider and other fruit wines",
		"11040" to "Manufacture of other non-distilled fermented beverages",
		"11050" to "Manufacture of beer",
		"11060" to "Manufacture of malt",
		"11070" to "Manufacture of soft drinks; production of mineral waters and other bottled waters",
		"12000" to "Manufacture of tobacco products",
		"13100" to "Preparation and spinning of textile fibres",
		"13200" to "Weaving of textiles",
		"13300" to "Finishing of textiles",
		"13910" to "Manufacture of knitted and crocheted fabrics",
		"13921" to "Manufacture of soft furnishings",
		"13922" to "manufacture of canvas goods, sacks, etc.",
		"13923" to "manufacture of household textiles",
		"13931" to "Manufacture of woven or tufted carpets and rugs",
		"13939" to "Manufacture of other carpets and rugs",
		"13940" to "Manufacture of cordage, rope, twine and netting",
		"13950" to "Manufacture of non-wovens and articles made from non-wovens, except apparel",
		"13960" to "Manufacture of other technical and industrial textiles",
		"13990" to "Manufacture of other textiles not elsewhere classified",
		"14110" to "Manufacture of leather clothes",
		"14120" to "Manufacture of workwear",
		"14131" to "Manufacture of other men's outerwear",
		"14132" to "Manufacture of other women's outerwear",
		"14141" to "Manufacture of men's underwear",
		"14142" to "Manufacture of women's underwear",
		"14190" to "Manufacture of other wearing apparel and accessories not elsewhere classified",
		"14200" to "Manufacture of articles of fur",
		"14310" to "Manufacture of knitted and crocheted hosiery",
		"14390" to "Manufacture of other knitted and crocheted apparel",
		"15110" to "Tanning and dressing of leather; dressing and dyeing of fur",
		"15120" to "Manufacture of luggage, handbags and the like, saddlery and harness",
		"15200" to "Manufacture of footwear",
		"16100" to "Sawmilling and planing of wood",
		"16210" to "Manufacture of veneer sheets and wood-based panels",
		"16220" to "Manufacture of assembled parquet floors",
		"16230" to "Manufacture of other builders' carpentry and joinery",
		"16240" to "Manufacture of wooden containers",
		"16290" to "Manufacture of other products of wood; manufacture of articles of cork, straw and plaiting materials",
		"17110" to "Manufacture of pulp",
		"17120" to "Manufacture of paper and paperboard",
		"17211" to "Manufacture of corrugated paper and paperboard, sacks and bags",
		"17219" to "Manufacture of other paper and paperboard containers",
		"17220" to "Manufacture of household and sanitary goods and of toilet requisites",
		"17230" to "Manufacture of paper stationery",
		"17240" to "Manufacture of wallpaper",
		"17290" to "Manufacture of other articles of paper and paperboard not elsewhere classified",
		"18110" to "Printing of newspapers",
		"18121" to "Manufacture of printed labels",
		"18129" to "Printing not elsewhere classified",
		"18130" to "Pre-press and pre-media services",
		"18140" to "Binding and related services",
		"18201" to "Reproduction of sound recording",
		"18202" to "Reproduction of video recording",
		"18203" to "Reproduction of computer media",
		"19100" to "Manufacture of coke oven products",
		"19201" to "Mineral oil refining",
		"19209" to "Other treatment of petroleum products (excluding petrochemicals manufacture)",
		"20110" to "Manufacture of industrial gases",
		"20120" to "Manufacture of dyes and pigments",
		"20130" to "Manufacture of other inorganic basic chemicals",
		"20140" to "Manufacture of other organic basic chemicals",
		"20150" to "Manufacture of fertilisers and nitrogen compounds",
		"20160" to "Manufacture of plastics in primary forms",
		"20170" to "Manufacture of synthetic rubber in primary forms",
		"20200" to "Manufacture of pesticides and other agrochemical products",
		"20301" to "Manufacture of paints, varnishes and similar coatings, mastics and sealants",
		"20302" to "Manufacture of printing ink",
		"20411" to "Manufacture of soap and detergents",
		"20412" to "Manufacture of cleaning and polishing preparations",
		"20420" to "Manufacture of perfumes and toilet preparations",
		"20510" to "Manufacture of explosives",
		"20520" to "Manufacture of glues",
		"20530" to "Manufacture of essential oils",
		"20590" to "Manufacture of other chemical products not elsewhere classified",
		"20600" to "Manufacture of man-made fibres",
		"21100" to "Manufacture of basic pharmaceutical products",
		"21200" to "Manufacture of pharmaceutical preparations",
		"22110" to "Manufacture of rubber tyres and tubes; retreading and rebuilding of rubber tyres",
		"22190" to "Manufacture of other rubber products",
		"22210" to "Manufacture of plastic plates, sheets, tubes and profiles",
		"22220" to "Manufacture of plastic packing goods",
		"22230" to "Manufacture of builders  ware of plastic",
		"22290" to "Manufacture of other plastic products",
		"23110" to "Manufacture of flat glass",
		"23120" to "Shaping and processing of flat glass",
		"23130" to "Manufacture of hollow glass",
		"23140" to "Manufacture of glass fibres",
		"23190" to "Manufacture and processing of other glass, including technical glassware",
		"23200" to "Manufacture of refractory products",
		"23310" to "Manufacture of ceramic tiles and flags",
		"23320" to "Manufacture of bricks, tiles and construction products, in baked clay",
		"23410" to "Manufacture of ceramic household and ornamental articles",
		"23420" to "Manufacture of ceramic sanitary fixtures",
		"23430" to "Manufacture of ceramic insulators and insulating fittings",
		"23440" to "Manufacture of other technical ceramic products",
		"23490" to "Manufacture of other ceramic products not elsewhere classified",
		"23510" to "Manufacture of cement",
		"23520" to "Manufacture of lime and plaster",
		"23610" to "Manufacture of concrete products for construction purposes",
		"23620" to "Manufacture of plaster products for construction purposes",
		"23630" to "Manufacture of ready-mixed concrete",
		"23640" to "Manufacture of mortars",
		"23650" to "Manufacture of fibre cement",
		"23690" to "Manufacture of other articles of concrete, plaster and cement",
		"23700" to "Cutting, shaping and finishing of stone",
		"23910" to "Production of abrasive products",
		"23990" to "Manufacture of other non-metallic mineral products not elsewhere classified",
		"24100" to "Manufacture of basic iron and steel and of ferro-alloys",
		"24200" to "Manufacture of tubes, pipes, hollow profiles and related fittings, of steel",
		"24310" to "Cold drawing of bars",
		"24320" to "Cold rolling of narrow strip",
		"24330" to "Cold forming or folding",
		"24340" to "Cold drawing of wire",
		"24410" to "Precious metals production",
		"24420" to "Aluminium production",
		"24430" to "Lead, zinc and tin production",
		"24440" to "Copper production",
		"24450" to "Other non-ferrous metal production",
		"24460" to "Processing of nuclear fuel",
		"24510" to "Casting of iron",
		"24520" to "Casting of steel",
		"24530" to "Casting of light metals",
		"24540" to "Casting of other non-ferrous metals",
		"25110" to "Manufacture of metal structures and parts of structures",
		"25120" to "Manufacture of doors and windows of metal",
		"25210" to "Manufacture of central heating radiators and boilers",
		"25290" to "Manufacture of other tanks, reservoirs and containers of metal",
		"25300" to "Manufacture of steam generators, except central heating hot water boilers",
		"25400" to "Manufacture of weapons and ammunition",
		"25500" to "Forging, pressing, stamping and roll-forming of metal; powder metallurgy",
		"25610" to "Treatment and coating of metals",
		"25620" to "Machining",
		"25710" to "Manufacture of cutlery",
		"25720" to "Manufacture of locks and hinges",
		"25730" to "Manufacture of tools",
		"25910" to "Manufacture of steel drums and similar containers",
		"25920" to "Manufacture of light metal packaging",
		"25930" to "Manufacture of wire products, chain and springs",
		"25940" to "Manufacture of fasteners and screw machine products",
		"25990" to "Manufacture of other fabricated metal products not elsewhere classified",
		"26110" to "Manufacture of electronic components",
		"26120" to "Manufacture of loaded electronic boards",
		"26200" to "Manufacture of computers and peripheral equipment",
		"26301" to "Manufacture of telegraph and telephone apparatus and equipment",
		"26309" to "Manufacture of communication equipment other than telegraph, and telephone apparatus and equipment",
		"26400" to "Manufacture of consumer electronics",
		"26511" to "Manufacture of electronic measuring, testing etc. equipment, not for industrial process control",
		"26512" to "Manufacture of electronic industrial process control equipment",
		"26513" to "Manufacture of non-electronic measuring, testing etc. equipment, not for industrial process control",
		"26514" to "Manufacture of non-electronic industrial process control equipment",
		"26520" to "Manufacture of watches and clocks",
		"26600" to "Manufacture of irradiation, electromedical and electrotherapeutic equipment",
		"26701" to "Manufacture of optical precision instruments",
		"26702" to "Manufacture of photographic and cinematographic equipment",
		"26800" to "Manufacture of magnetic and optical media",
		"27110" to "Manufacture of electric motors, generators and transformers",
		"27120" to "Manufacture of electricity distribution and control apparatus",
		"27200" to "Manufacture of batteries and accumulators",
		"27310" to "Manufacture of fibre optic cables",
		"27320" to "Manufacture of other electronic and electric wires and cables",
		"27330" to "Manufacture of wiring devices",
		"27400" to "Manufacture of electric lighting equipment",
		"27510" to "Manufacture of electric domestic appliances",
		"27520" to "Manufacture of non-electric domestic appliances",
		"27900" to "Manufacture of other electrical equipment",
		"28110" to "Manufacture of engines and turbines, except aircraft, vehicle and cycle engines",
		"28120" to "Manufacture of fluid power equipment",
		"28131" to "Manufacture of pumps",
		"28132" to "Manufacture of compressors",
		"28140" to "Manufacture of taps and valves",
		"28150" to "Manufacture of bearings, gears, gearing and driving elements",
		"28210" to "Manufacture of ovens, furnaces and furnace burners",
		"28220" to "Manufacture of lifting and handling equipment",
		"28230" to "Manufacture of office machinery and equipment (except computers and peripheral equipment)",
		"28240" to "Manufacture of power-driven hand tools",
		"28250" to "Manufacture of non-domestic cooling and ventilation equipment",
		"28290" to "Manufacture of other general-purpose machinery not elsewhere classified",
		"28301" to "Manufacture of agricultural tractors",
		"28302" to "Manufacture of agricultural and forestry machinery other than tractors",
		"28410" to "Manufacture of metal forming machinery",
		"28490" to "Manufacture of other machine tools",
		"28910" to "Manufacture of machinery for metallurgy",
		"28921" to "Manufacture of machinery for mining",
		"28922" to "Manufacture of earthmoving equipment",
		"28923" to "Manufacture of equipment for concrete crushing and screening and roadworks",
		"28930" to "Manufacture of machinery for food, beverage and tobacco processing",
		"28940" to "Manufacture of machinery for textile, apparel and leather production",
		"28950" to "Manufacture of machinery for paper and paperboard production",
		"28960" to "Manufacture of plastics and rubber machinery",
		"28990" to "Manufacture of other special-purpose machinery not elsewhere classified",
		"29100" to "Manufacture of motor vehicles",
		"29201" to "Manufacture of bodies (coachwork) for motor vehicles (except caravans)",
		"29202" to "Manufacture of trailers and semi-trailers",
		"29203" to "Manufacture of caravans",
		"29310" to "Manufacture of electrical and electronic equipment for motor vehicles and their engines",
		"29320" to "Manufacture of other parts and accessories for motor vehicles",
		"30110" to "Building of ships and floating structures",
		"30120" to "Building of pleasure and sporting boats",
		"30200" to "Manufacture of railway locomotives and rolling stock",
		"30300" to "Manufacture of air and spacecraft and related machinery",
		"30400" to "Manufacture of military fighting vehicles",
		"30910" to "Manufacture of motorcycles",
		"30920" to "Manufacture of bicycles and invalid carriages",
		"30990" to "Manufacture of other transport equipment not elsewhere classified",
		"31010" to "Manufacture of office and shop furniture",
		"31020" to "Manufacture of kitchen furniture",
		"31030" to "Manufacture of mattresses",
		"31090" to "Manufacture of other furniture",
		"32110" to "Striking of coins",
		"32120" to "Manufacture of jewellery and related articles",
		"32130" to "Manufacture of imitation jewellery and related articles",
		"32200" to "Manufacture of musical instruments",
		"32300" to "Manufacture of sports goods",
		"32401" to "Manufacture of professional and arcade games and toys",
		"32409" to "Manufacture of other games and toys, not elsewhere classified",
		"32500" to "Manufacture of medical and dental instruments and supplies",
		"32910" to "Manufacture of brooms and brushes",
		"32990" to "Other manufacturing not elsewhere classified",
		"33110" to "Repair of fabricated metal products",
		"33120" to "Repair of machinery",
		"33130" to "Repair of electronic and optical equipment",
		"33140" to "Repair of electrical equipment",
		"33150" to "Repair and maintenance of ships and boats",
		"33160" to "Repair and maintenance of aircraft and spacecraft",
		"33170" to "Repair and maintenance of other transport equipment not elsewhere classified",
		"33190" to "Repair of other equipment",
		"33200" to "Installation of industrial machinery and equipment",
		"35110" to "Production of electricity",
		"35120" to "Transmission of electricity",
		"35130" to "Distribution of electricity",
		"35140" to "Trade of electricity",
		"35210" to "Manufacture of gas",
		"35220" to "Distribution of gaseous fuels through mains",
		"35230" to "Trade of gas through mains",
		"35300" to "Steam and air conditioning supply",
		"36000" to "Water collection, treatment and supply",
		"37000" to "Sewerage",
		"38110" to "Collection of non-hazardous waste",
		"38120" to "Collection of hazardous waste",
		"38210" to "Treatment and disposal of non-hazardous waste",
		"38220" to "Treatment and disposal of hazardous waste",
		"38310" to "Dismantling of wrecks",
		"38320" to "Recovery of sorted materials",
		"39000" to "Remediation activities and other waste management services",
		"41100" to "Development of building projects",
		"41201" to "Construction of commercial buildings",
		"41202" to "Construction of domestic buildings",
		"42110" to "Construction of roads and motorways",
		"42120" to "Construction of railways and underground railways",
		"42130" to "Construction of bridges and tunnels",
		"42210" to "Construction of utility projects for fluids",
		"42220" to "Construction of utility projects for electricity and telecommunications",
		"42910" to "Construction of water projects",
		"42990" to "Construction of other civil engineering projects not elsewhere classified",
		"43110" to "Demolition",
		"43120" to "Site preparation",
		"43130" to "Test drilling and boring",
		"43210" to "Electrical installation",
		"43220" to "Plumbing, heat and air-conditioning installation",
		"43290" to "Other construction installation",
		"43310" to "Plastering",
		"43320" to "Joinery installation",
		"43330" to "Floor and wall covering",
		"43341" to "Painting",
		"43342" to "Glazing",
		"43390" to "Other building completion and finishing",
		"43910" to "Roofing activities",
		"43991" to "Scaffold erection",
		"43999" to "Other specialised construction activities not elsewhere classified",
		"45111" to "Sale of new cars and light motor vehicles",
		"45112" to "Sale of used cars and light motor vehicles",
		"45190" to "Sale of other motor vehicles",
		"45200" to "Maintenance and repair of motor vehicles",
		"45310" to "Wholesale trade of motor vehicle parts and accessories",
		"45320" to "Retail trade of motor vehicle parts and accessories",
		"45400" to "Sale, maintenance and repair of motorcycles and related parts and accessories",
		"46110" to "Agents selling agricultural raw materials, livestock, textile raw materials and semi-finished goods",
		"46120" to "Agents involved in the sale of fuels, ores, metals and industrial chemicals",
		"46130" to "Agents involved in the sale of timber and building materials",
		"46140" to "Agents involved in the sale of machinery, industrial equipment, ships and aircraft",
		"46150" to "Agents involved in the sale of furniture, household goods, hardware and ironmongery",
		"46160" to "Agents involved in the sale of textiles, clothing, fur, footwear and leather goods",
		"46170" to "Agents involved in the sale of food, beverages and tobacco",
		"46180" to "Agents specialised in the sale of other particular products",
		"46190" to "Agents involved in the sale of a variety of goods",
		"46210" to "Wholesale of grain, unmanufactured tobacco, seeds and animal feeds",
		"46220" to "Wholesale of flowers and plants",
		"46230" to "Wholesale of live animals",
		"46240" to "Wholesale of hides, skins and leather",
		"46310" to "Wholesale of fruit and vegetables",
		"46320" to "Wholesale of meat and meat products",
		"46330" to "Wholesale of dairy products, eggs and edible oils and fats",
		"46341" to "Wholesale of fruit and vegetable juices, mineral water and soft drinks",
		"46342" to "Wholesale of wine, beer, spirits and other alcoholic beverages",
		"46350" to "Wholesale of tobacco products",
		"46360" to "Wholesale of sugar and chocolate and sugar confectionery",
		"46370" to "Wholesale of coffee, tea, cocoa and spices",
		"46380" to "Wholesale of other food, including fish, crustaceans and molluscs",
		"46390" to "Non-specialised wholesale of food, beverages and tobacco",
		"46410" to "Wholesale of textiles",
		"46420" to "Wholesale of clothing and footwear",
		"46431" to "Wholesale of audio tapes, records, CDs and video tapes and the equipment on which these are played",
		"46439" to
			"Wholesale of radio, television goods & electrical household appliances " +
			"(other than records, tapes, CD's & video tapes and the equipment used for playing them)",
		"46440" to "Wholesale of china and glassware and cleaning materials",
		"46450" to "Wholesale of perfume and cosmetics",
		"46460" to "Wholesale of pharmaceutical goods",
		"46470" to "Wholesale of furniture, carpets and lighting equipment",
		"46480" to "Wholesale of watches and jewellery",
		"46491" to "Wholesale of musical instruments",
		"46499" to "Wholesale of household goods (other than musical instruments) not elsewhere classified",
		"46510" to "Wholesale of computers, computer peripheral equipment and software",
		"46520" to "Wholesale of electronic and telecommunications equipment and parts",
		"46610" to "Wholesale of agricultural machinery, equipment and supplies",
		"46620" to "Wholesale of machine tools",
		"46630" to "Wholesale of mining, construction and civil engineering machinery",
		"46640" to "Wholesale of machinery for the textile industry and of sewing and knitting machines",
		"46650" to "Wholesale of office furniture",
		"46660" to "Wholesale of other office machinery and equipment",
		"46690" to "Wholesale of other machinery and equipment",
		"46711" to "Wholesale of petroleum and petroleum products",
		"46719" to "Wholesale of other fuels and related products",
		"46720" to "Wholesale of metals and metal ores",
		"46730" to "Wholesale of wood, construction materials and sanitary equipment",
		"46740" to "Wholesale of hardware, plumbing and heating equipment and supplies",
		"46750" to "Wholesale of chemical products",
		"46760" to "Wholesale of other intermediate products",
		"46770" to "Wholesale of waste and scrap",
		"46900" to "Non-specialised wholesale trade",
		"47110" to "Retail sale in non-specialised stores with food, beverages or tobacco predominating",
		"47190" to "Other retail sale in non-specialised stores",
		"47210" to "Retail sale of fruit and vegetables in specialised stores",
		"47220" to "Retail sale of meat and meat products in specialised stores",
		"47230" to "Retail sale of fish, crustaceans and molluscs in specialised stores",
		"47240" to "Retail sale of bread, cakes, flour confectionery and sugar confectionery in specialised stores",
		"47250" to "Retail sale of beverages in specialised stores",
		"47260" to "Retail sale of tobacco products in specialised stores",
		"47290" to "Other retail sale of food in specialised stores",
		"47300" to "Retail sale of automotive fuel in specialised stores",
		"47410" to "Retail sale of computers, peripheral units and software in specialised stores",
		"47421" to "Retail sale of mobile telephones",
		"47429" to "Retail sale of telecommunications equipment other than mobile telephones",
		"47430" to "Retail sale of audio and video equipment in specialised stores",
		"47510" to "Retail sale of textiles in specialised stores",
		"47520" to "Retail sale of hardware, paints and glass in specialised stores",
		"47530" to "Retail sale of carpets, rugs, wall and floor coverings in specialised stores",
		"47540" to "Retail sale of electrical household appliances in specialised stores",
		"47591" to "Retail sale of musical instruments and scores",
		"47599" to "Retail of furniture, lighting, and similar (not musical instruments or scores) in specialised store",
		"47610" to "Retail sale of books in specialised stores",
		"47620" to "Retail sale of newspapers and stationery in specialised stores",
		"47630" to "Retail sale of music and video recordings in specialised stores",
		"47640" to "Retail sale of sports goods, fishing gear, camping goods, boats and bicycles",
		"47650" to "Retail sale of games and toys in specialised stores",
		"47710" to "Retail sale of clothing in specialised stores",
		"47721" to "Retail sale of footwear in specialised stores",
		"47722" to "Retail sale of leather goods in specialised stores",
		"47730" to "Dispensing chemist in specialised stores",
		"47741" to "Retail sale of hearing aids",
		"47749" to "Retail sale of medical and orthopaedic goods in specialised stores " +
			"(not incl. hearing aids) not elsewhere classified",
		"47750" to "Retail sale of cosmetic and toilet articles in specialised stores",
		"47760" to "Retail sale of flowers, plants, seeds, fertilisers, pet animals and pet food in specialised stores",
		"47770" to "Retail sale of watches and jewellery in specialised stores",
		"47781" to "Retail sale in commercial art galleries",
		"47782" to "Retail sale by opticians",
		"47789" to "Other retail sale of new goods in specialised stores (not commercial art galleries and opticians)",
		"47791" to "Retail sale of antiques including antique books in stores",
		"47799" to "Retail sale of other second-hand goods in stores (not incl. antiques)",
		"47810" to "Retail sale via stalls and markets of food, beverages and tobacco products",
		"47820" to "Retail sale via stalls and markets of textiles, clothing and footwear",
		"47890" to "Retail sale via stalls and markets of other goods",
		"47910" to "Retail sale via mail order houses or via Internet",
		"47990" to "Other retail sale not in stores, stalls or markets",
		"49100" to "Passenger rail transport, interurban",
		"49200" to "Freight rail transport",
		"49311" to "Urban and suburban passenger railway transportation by underground, metro and similar systems",
		"49319" to "Other urban, suburban or metropolitan passenger land transport (not underground, metro or similar)",
		"49320" to "Taxi operation",
		"49390" to "Other passenger land transport",
		"49410" to "Freight transport by road",
		"49420" to "Removal services",
		"49500" to "Transport via pipeline",
		"50100" to "Sea and coastal passenger water transport",
		"50200" to "Sea and coastal freight water transport",
		"50300" to "Inland passenger water transport",
		"50400" to "Inland freight water transport",
		"51101" to "Scheduled passenger air transport",
		"51102" to "Non-scheduled passenger air transport",
		"51210" to "Freight air transport",
		"51220" to "Space transport",
		"52101" to "Operation of warehousing and storage facilities for water transport activities",
		"52102" to "Operation of warehousing and storage facilities for air transport activities",
		"52103" to "Operation of warehousing and storage facilities for land transport activities",
		"52211" to "Operation of rail freight terminals",
		"52212" to "Operation of rail passenger facilities at railway stations",
		"52213" to "Operation of bus and coach passenger facilities at bus and coach stations",
		"52219" to "Other service activities incidental to land transportation, not elsewhere classified",
		"52220" to "Service activities incidental to water transportation",
		"52230" to "Service activities incidental to air transportation",
		"52241" to "Cargo handling for water transport activities",
		"52242" to "Cargo handling for air transport activities",
		"52243" to "Cargo handling for land transport activities",
		"52290" to "Other transportation support activities",
		"53100" to "Postal activities under universal service obligation",
		"53201" to "Licensed carriers",
		"53202" to "Unlicensed carrier",
		"55100" to "Hotels and similar accommodation",
		"55201" to "Holiday centres and villages",
		"55202" to "Youth hostels",
		"55209" to "Other holiday and other collective accommodation",
		"55300" to "Recreational vehicle parks, trailer parks and camping grounds",
		"55900" to "Other accommodation",
		"56101" to "Licensed restaurants",
		"56102" to "Unlicensed restaurants and cafes",
		"56103" to "Take-away food shops and mobile food stands",
		"56210" to "Event catering activities",
		"56290" to "Other food services",
		"56301" to "Licensed clubs",
		"56302" to "Public houses and bars",
		"58110" to "Book publishing",
		"58120" to "Publishing of directories and mailing lists",
		"58130" to "Publishing of newspapers",
		"58141" to "Publishing of learned journals",
		"58142" to "Publishing of  consumer and business journals and periodicals",
		"58190" to "Other publishing activities",
		"58210" to "Publishing of computer games",
		"58290" to "Other software publishing",
		"59111" to "Motion picture production activities",
		"59112" to "Video production activities",
		"59113" to "Television programme production activities",
		"59120" to "Motion picture, video and television programme post-production activities",
		"59131" to "Motion picture distribution activities",
		"59132" to "Video distribution activities",
		"59133" to "Television programme distribution activities",
		"59140" to "Motion picture projection activities",
		"59200" to "Sound recording and music publishing activities",
		"60100" to "Radio broadcasting",
		"60200" to "Television programming and broadcasting activities",
		"61100" to "Wired telecommunications activities",
		"61200" to "Wireless telecommunications activities",
		"61300" to "Satellite telecommunications activities",
		"61900" to "Other telecommunications activities",
		"62011" to "Ready-made interactive leisure and entertainment software development",
		"62012" to "Business and domestic software development",
		"62020" to "Information technology consultancy activities",
		"62030" to "Computer facilities management activities",
		"62090" to "Other information technology service activities",
		"63110" to "Data processing, hosting and related activities",
		"63120" to "Web portals",
		"63910" to "News agency activities",
		"63990" to "Other information service activities not elsewhere classified",
		"64110" to "Central banking",
		"64191" to "Banks",
		"64192" to "Building societies",
		"64201" to "Activities of agricultural holding companies",
		"64202" to "Activities of production holding companies",
		"64203" to "Activities of construction holding companies",
		"64204" to "Activities of distribution holding companies",
		"64205" to "Activities of financial services holding companies",
		"64209" to "Activities of other holding companies not elsewhere classified",
		"64301" to "Activities of investment trusts",
		"64302" to "Activities of unit trusts",
		"64303" to "Activities of venture and development capital companies",
		"64304" to "Activities of open-ended investment companies",
		"64305" to "Activities of property unit trusts",
		"64306" to "Activities of real estate investment trusts",
		"64910" to "Financial leasing",
		"64921" to "Credit granting by non-deposit taking finance houses and other specialist consumer credit grantors",
		"64922" to "Activities of mortgage finance companies",
		"64929" to "Other credit granting not elsewhere classified",
		"64991" to "Security dealing on own account",
		"64992" to "Factoring",
		"64999" to "Financial intermediation not elsewhere classified",
		"65110" to "Life insurance",
		"65120" to "Non-life insurance",
		"65201" to "Life reinsurance",
		"65202" to "Non-life reinsurance",
		"65300" to "Pension funding",
		"66110" to "Administration of financial markets",
		"66120" to "Security and commodity contracts dealing activities",
		"66190" to "Activities auxiliary to financial intermediation not elsewhere classified",
		"66210" to "Risk and damage evaluation",
		"66220" to "Activities of insurance agents and brokers",
		"66290" to "Other activities auxiliary to insurance and pension funding",
		"66300" to "Fund management activities",
		"68100" to "Buying and selling of own real estate",
		"68201" to "Renting and operating of Housing Association real estate",
		"68202" to "Letting and operating of conference and exhibition centres",
		"68209" to "Other letting and operating of own or leased real estate",
		"68310" to "Real estate agencies",
		"68320" to "Management of real estate on a fee or contract basis",
		"69101" to "Barristers at law",
		"69102" to "Solicitors",
		"69109" to "Activities of patent and copyright agents; other legal activities not elsewhere classified",
		"69201" to "Accounting and auditing activities",
		"69202" to "Bookkeeping activities",
		"69203" to "Tax consultancy",
		"70100" to "Activities of head offices",
		"70210" to "Public relations and communications activities",
		"70221" to "Financial management",
		"70229" to "Management consultancy activities other than financial management",
		"71111" to "Architectural activities",
		"71112" to "Urban planning and landscape architectural activities",
		"71121" to "Engineering design activities for industrial process and production",
		"71122" to "Engineering related scientific and technical consulting activities",
		"71129" to "Other engineering activities",
		"71200" to "Technical testing and analysis",
		"72110" to "Research and experimental development on biotechnology",
		"72190" to "Other research and experimental development on natural sciences and engineering",
		"72200" to "Research and experimental development on social sciences and humanities",
		"73110" to "Advertising agencies",
		"73120" to "Media representation services",
		"73200" to "Market research and public opinion polling",
		"74100" to "Specialised design activities",
		"74201" to "Portrait photographic activities",
		"74202" to "Other specialist photography",
		"74203" to "Film processing",
		"74209" to "Photographic activities not elsewhere classified",
		"74300" to "Translation and interpretation activities",
		"74901" to "Environmental consulting activities",
		"74902" to "Quantity surveying activities",
		"74909" to "Other professional, scientific and technical activities not elsewhere classified",
		"74990" to "Non-trading company",
		"75000" to "Veterinary activities",
		"77110" to "Renting and leasing of cars and light motor vehicles",
		"77120" to "Renting and leasing of trucks and other heavy vehicles",
		"77210" to "Renting and leasing of recreational and sports goods",
		"77220" to "Renting of video tapes and disks",
		"77291" to "Renting and leasing of media entertainment equipment",
		"77299" to "Renting and leasing of other personal and household goods",
		"77310" to "Renting and leasing of agricultural machinery and equipment",
		"77320" to "Renting and leasing of construction and civil engineering machinery and equipment",
		"77330" to "Renting and leasing of office machinery and equipment (including computers)",
		"77341" to "Renting and leasing of passenger water transport equipment",
		"77342" to "Renting and leasing of freight water transport equipment",
		"77351" to "Renting and leasing of air passenger transport equipment",
		"77352" to "Renting and leasing of freight air transport equipment",
		"77390" to "Renting and leasing of other machinery, equipment and tangible goods not elsewhere classified",
		"77400" to "Leasing of intellectual property and similar products, except copyright works",
		"78101" to "Motion picture, television and other theatrical casting activities",
		"78109" to "Other activities of employment placement agencies",
		"78200" to "Temporary employment agency activities",
		"78300" to "Human resources provision and management of human resources functions",
		"79110" to "Travel agency activities",
		"79120" to "Tour operator activities",
		"79901" to "Activities of tourist guides",
		"79909" to "Other reservation service activities not elsewhere classified",
		"80100" to "Private security activities",
		"80200" to "Security systems service activities",
		"80300" to "Investigation activities",
		"81100" to "Combined facilities support activities",
		"81210" to "General cleaning of buildings",
		"81221" to "Window cleaning services",
		"81222" to "Specialised cleaning services",
		"81223" to "Furnace and chimney cleaning services",
		"81229" to "Other building and industrial cleaning activities",
		"81291" to "Disinfecting and exterminating services",
		"81299" to "Other cleaning services",
		"81300" to "Landscape service activities",
		"82110" to "Combined office administrative service activities",
		"82190" to "Photocopying, document preparation and other specialised office support activities",
		"82200" to "Activities of call centres",
		"82301" to "Activities of exhibition and fair organisers",
		"82302" to "Activities of conference organisers",
		"82911" to "Activities of collection agencies",
		"82912" to "Activities of credit bureaus",
		"82920" to "Packaging activities",
		"82990" to "Other business support service activities not elsewhere classified",
		"84110" to "General public administration activities",
		"84120" to "Regulation of health care, education, cultural and other social services, not incl. social security",
		"84130" to "Regulation of and contribution to more efficient operation of businesses",
		"84210" to "Foreign affairs",
		"84220" to "Defence activities",
		"84230" to "Justice and judicial activities",
		"84240" to "Public order and safety activities",
		"84250" to "Fire service activities",
		"84300" to "Compulsory social security activities",
		"85100" to "Pre-primary education",
		"85200" to "Primary education",
		"85310" to "General secondary education",
		"85320" to "Technical and vocational secondary education",
		"85410" to "Post-secondary non-tertiary education",
		"85421" to "First-degree level higher education",
		"85422" to "Post-graduate level higher education",
		"85510" to "Sports and recreation education",
		"85520" to "Cultural education",
		"85530" to "Driving school activities",
		"85590" to "Other education not elsewhere classified",
		"85600" to "Educational support services",
		"86101" to "Hospital activities",
		"86102" to "Medical nursing home activities",
		"86210" to "General medical practice activities",
		"86220" to "Specialists medical practice activities",
		"86230" to "Dental practice activities",
		"86900" to "Other human health activities",
		"87100" to "Residential nursing care facilities",
		"87200" to "Residential care activities for learning difficulties, mental health and substance abuse",
		"87300" to "Residential care activities for the elderly and disabled",
		"87900" to "Other residential care activities not elsewhere classified",
		"88100" to "Social work activities without accommodation for the elderly and disabled",
		"88910" to "Child day-care activities",
		"88990" to "Other social work activities without accommodation not elsewhere classified",
		"90010" to "Performing arts",
		"90020" to "Support activities to performing arts",
		"90030" to "Artistic creation",
		"90040" to "Operation of arts facilities",
		"91011" to "Library activities",
		"91012" to "Archives activities",
		"91020" to "Museums activities",
		"91030" to "Operation of historical sites and buildings and similar visitor attractions",
		"91040" to "Botanical and zoological gardens and nature reserves activities",
		"92000" to "Gambling and betting activities",
		"93110" to "Operation of sports facilities",
		"93120" to "Activities of sport clubs",
		"93130" to "Fitness facilities",
		"93191" to "Activities of racehorse owners",
		"93199" to "Other sports activities",
		"93210" to "Activities of amusement parks and theme parks",
		"93290" to "Other amusement and recreation activities not elsewhere classified",
		"94110" to "Activities of business and employers membership organisations",
		"94120" to "Activities of professional membership organisations",
		"94200" to "Activities of trade unions",
		"94910" to "Activities of religious organisations",
		"94920" to "Activities of political organisations",
		"94990" to "Activities of other membership organisations not elsewhere classified",
		"95110" to "Repair of computers and peripheral equipment",
		"95120" to "Repair of communication equipment",
		"95210" to "Repair of consumer electronics",
		"95220" to "Repair of household appliances and home and garden equipment",
		"95230" to "Repair of footwear and leather goods",
		"95240" to "Repair of furniture and home furnishings",
		"95250" to "Repair of watches, clocks and jewellery",
		"95290" to "Repair of personal and household goods not elsewhere classified",
		"96010" to "Washing and (dry-)cleaning of textile and fur products",
		"96020" to "Hairdressing and other beauty treatment",
		"96030" to "Funeral and related activities",
		"96040" to "Physical well-being activities",
		"96090" to "Other service activities not elsewhere classified",
		"97000" to "Activities of households as employers of domestic personnel",
		"98000" to "Residents property management",
		"98100" to "Undifferentiated goods-producing activities of private households for own use",
		"98200" to "Undifferentiated service-producing activities of private households for own use",
		"99000" to "Activities of extraterritorial organisations and bodies",
		"99999" to "Dormant Company",
		"0111" to "Grow cereals & other crops",
		"0112" to "Grow vegetables & nursery products",
		"0113" to "Grow fruit, nuts, beverage & spice crops",
		"0121" to "Farming of cattle, dairy farming",
		"0122" to "Farm sheep, goats, horses, etc.",
		"0123" to "Farming of swine",
		"0124" to "Farming of poultry",
		"0125" to "Other farming of animals",
		"0130" to "Crops combined with animals, mixed farms",
		"0141" to "Agricultural service activities",
		"0142" to "Animal husbandry services, not vets",
		"0150" to "Hunting and game rearing inc. services",
		"0201" to "Forestry & logging",
		"0202" to "Forestry & logging related services",
		"0501" to "Fishing",
		"0502" to "Operation of fish hatcheries & farms",
		"01110" to "Growing of cereals (except rice), leguminous crops and oil seeds",
		"01120" to "Growing of rice",
		"01130" to "Growing of vegetables and melons, roots and tubers",
		"01140" to "Growing of sugar cane",
		"01150" to "Growing of tobacco",
		"01160" to "Growing of fibre crops",
		"01190" to "Growing of other non-perennial crops",
		"01210" to "Growing of grapes",
		"01220" to "Growing of tropical and subtropical fruits",
		"01230" to "Growing of citrus fruits",
		"01240" to "Growing of pome fruits and stone fruits",
		"01250" to "Growing of other tree and bush fruits and nuts",
		"01260" to "Growing of oleaginous fruits",
		"01270" to "Growing of beverage crops",
		"01280" to "Growing of spices, aromatic, drug and pharmaceutical crops",
		"01290" to "Growing of other perennial crops",
		"01300" to "Plant propagation",
		"01410" to "Raising of dairy cattle",
		"01420" to "Raising of other cattle and buffaloes",
		"01430" to "Raising of horses and other equines",
		"01440" to "Raising of camels and camelids",
		"01450" to "Raising of sheep and  goats",
		"01460" to "Raising of swine/pigs",
		"01470" to "Raising of poultry",
		"01490" to "Raising of other animals",
		"01500" to "Mixed farming",
		"01610" to "Support activities for crop production",
		"01621" to "Farm animal boarding and care",
		"01629" to
			"Support activities for animal production " +
			"(other than farm animal boarding and care) not elsewhere classified",
		"01630" to "Post-harvest crop activities",
		"01640" to "Seed processing for propagation",
		"01700" to "Hunting, trapping and related service activities",
		"02100" to "Silviculture and other forestry activities",
		"02200" to "Logging",
		"02300" to "Gathering of wild growing non-wood products",
		"02400" to "Support services to forestry",
		"03110" to "Marine fishing",
		"03120" to "Freshwater fishing",
		"03210" to "Marine aquaculture",
		"03220" to "Freshwater aquaculture",
		"05101" to "Deep coal mines",
		"05102" to "Open cast coal working",
		"05200" to "Mining of lignite",
		"06100" to "Extraction of crude petroleum",
		"06200" to "Extraction of natural gas",
		"07100" to "Mining of iron ores",
		"07210" to "Mining of uranium and thorium ores",
		"07290" to "Mining of other non-ferrous metal ores",
		"08110" to "Quarrying of ornamental and building stone, limestone, gypsum, chalk and slate",
		"08120" to "Operation of gravel and sand pits; mining of clays and kaolin",
		"08910" to "Mining of chemical and fertiliser minerals",
		"08920" to "Extraction of peat",
		"08930" to "Extraction of salt",
		"08990" to "Other mining and quarrying not elsewhere classified",
		"09100" to "Support activities for petroleum and natural gas extraction",
		"09900" to "Support activities for other mining and quarrying"
	)

	val notes = mapOf(
		"scottish-insolvency-info" to
			"The law requires some Scottish company and LLP insolvency documents be filed with the " +
			"Accountant in Bankruptcy (AIB). Find further details at " +
			"[[AIB's register of insolvent companies]](http://roi.aib.gov.uk/ROI/)"
	)

	val cessationLabelForStatus = mapOf(
		"dissolved" to "Dissolved on",
		"converted-closed" to "Closed on"
	)

	val registerLocations = mapOf(
		"registered-office" to "Registered office address",
		"single-alternative-inspection-location" to "Registered inspection location",
		"public-register" to "Public register",
		"unspecified-location" to "Not on the public register"
	)

	val registerTypes = mapOf(
		"directors" to "Directors",
		"secretaries" to "Secretaries",
		"persons-with-significant-control" to "Person(s) with significant control (PSCs)",
		"usual-residential-address" to "Usual residential addresses",
		"members" to "Members",
		"llp-members" to "Members",
		"llp-usual-residential-address" to "Usual residential addresses"
	)

	val partialDataAvailable = mapOf(
		"full-data-available-from-financial-conduct-authority" to
			"Refer to the Financial Conduct Authority for further information about this company",
		"full-data-available-from-department-of-the-economy" to
			"Refer to the Department of the Economy for further information about this company",
		"full-data-available-from-the-company" to "Contact the company directly for further information",
		"full-data-available-from-financial-conduct-authority-mutuals-public-register" to
			"Refer to the Financial Conduct Authority Mutuals Public Register for further information about this company"
	)

}
