@file:Suppress("unused")

package com.babestudios.companyinfouk.design

const val LIGHT_PRIMARY = 0xFF006D42
const val LIGHT_ON_PRIMARY = 0xFFffffff
const val LIGHT_PRIMARY_CONTAINER = 0xFF93F7BB
const val LIGHT_ON_PRIMARY_CONTAINER = 0xFF002111
const val LIGHT_SECONDARY = 0xFF00677C
const val LIGHT_ON_SECONDARY = 0xFFffffff
const val LIGHT_SECONDARY_CONTAINER = 0xFFB1EBFF
const val LIGHT_ON_SECONDARY_CONTAINER = 0xFF001F27
const val LIGHT_TERTIARY = 0xFF993F62
const val LIGHT_ON_TERTIARY = 0xFFffffff
const val LIGHT_TERTIARY_CONTAINER = 0xFFFFD9E3
const val LIGHT_ON_TERTIARY_CONTAINER = 0xFF3E001E
const val LIGHT_ERROR = 0xFFba1b1b
const val LIGHT_ERROR_CONTAINER = 0xFFffdad4
const val LIGHT_ON_ERROR = 0xFFffffff
const val LIGHT_ON_ERROR_CONTAINER = 0xFF410001
const val LIGHT_BACKGROUND = 0xFFfdfbff
const val LIGHT_ON_BACKGROUND = 0xFF1b1b1d
const val LIGHT_SURFACE = 0xFFfdfbff
const val LIGHT_ON_SURFACE = 0xFF1b1b1d
const val LIGHT_SURFACE_VARIANT = 0xFFdfe2eb
const val LIGHT_ON_SURFACE_VARIANT = 0xFF43474e
const val LIGHT_OUTLINE = 0xFF74777f
const val LIGHT_INVERSE_ON_SURFACE = 0xFFf1f0f4
const val LIGHT_INVERSE_SURFACE = 0xFF2f3033

const val DARK_PRIMARY = 0xFFa4c8ff
const val DARK_ON_PRIMARY = 0xFF003060
const val DARK_PRIMARY_CONTAINER = 0xFF004788
const val DARK_ON_PRIMARY_CONTAINER = 0xFFd3e3ff
const val DARK_SECONDARY = 0xFFbcc7dc
const val DARK_ON_SECONDARY = 0xFF273141
const val DARK_SECONDARY_CONTAINER = 0xFF3d4758
const val DARK_ON_SECONDARY_CONTAINER = 0xFFd8e3f8
const val DARK_TERTIARY = 0xFFdabde2
const val DARK_ON_TERTIARY = 0xFF3d2846
const val DARK_TERTIARY_CONTAINER = 0xFF553f5d
const val DARK_ON_TERTIARY_CONTAINER = 0xFFf7d8ff
const val DARK_ERROR = 0xFFffb4a9
const val DARK_ERROR_CONTAINER = 0xFF930006
const val DARK_ON_ERROR = 0xFF680003
const val DARK_ON_ERROR_CONTAINER = 0xFFffdad4
const val DARK_BACKGROUND = 0xFF1b1b1d
const val DARK_ON_BACKGROUND = 0xFFe3e2e6
const val DARK_SURFACE = 0xFF1b1b1d
const val DARK_ON_SURFACE = 0xFFe3e2e6
const val DARK_SURFACE_VARIANT = 0xFF43474e
const val DARK_ON_SURFACE_VARIANT = 0xFFc3c6cf
const val DARK_OUTLINE = 0xFF8e919a
const val DARK_INVERSE_ON_SURFACE = 0xFF1b1b1d
const val DARK_INVERSE_SURFACE = 0xFFe3e2e6

const val SEMI_TRANSPARENT = 0x88000000
const val TRANSLUCENT_BLACK = 0x33000000
const val SEMI_TRANSPARENT_GREY = 0x66999999
const val SEMI_TRANSPARENT_WHITE = 0x80ffffff
const val TRANSLUCENT_WHITE = 0x33ffffff
const val CLOUDY_WHITE = 0xccffffff
